import { DocsLayout } from "@/components/docs/DocsLayout";
import { CodeBlock } from "@/components/docs/CodeBlock";
import { FileBox, Image, Layers } from "lucide-react";

const ExportFormats = () => {
  return (
    <DocsLayout>
      <div className="prose prose-invert max-w-none">
        <h1 id="export-formats" className="text-3xl font-bold text-white mb-4">
          Export Formats
        </h1>
        <p className="text-lg text-white/70 mb-8">
          Detailed specifications for GLB, OBJ, and PNG export formats generated by 
          the CityEngine integration pipeline.
        </p>

        <h2 id="glb-format" className="text-2xl font-semibold text-white mt-12 mb-4">
          <FileBox className="inline h-6 w-6 mr-2 text-[hsl(var(--feasibility-orange))]" />
          GLB Format
        </h2>
        <p className="text-white/70 mb-4">
          GLB (Binary glTF) is the primary format for web-based 3D visualization. 
          It's a self-contained binary format that includes geometry, materials, 
          and textures in a single file.
        </p>

        <div className="p-4 rounded-lg border border-white/10 bg-white/5 mb-6">
          <h4 className="text-white font-medium mb-3">Specifications</h4>
          <ul className="space-y-2 text-sm text-white/70">
            <li>• <strong>glTF Version:</strong> 2.0</li>
            <li>• <strong>Coordinate System:</strong> Y-up, meters</li>
            <li>• <strong>Materials:</strong> PBR metallic-roughness</li>
            <li>• <strong>Typical Size:</strong> 2-10 MB</li>
            <li>• <strong>Compression:</strong> Draco mesh compression (optional)</li>
          </ul>
        </div>

        <CodeBlock
          code={`// Load GLB in Three.js
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';

const loader = new GLTFLoader();
loader.load(signedUrl, (gltf) => {
  scene.add(gltf.scene);
  
  // Access building metadata
  const building = gltf.scene.getObjectByName('massing');
  console.log(building.userData); // { height_ft, far, gross_sf }
});`}
          language="typescript"
          title="Three.js Loading Example"
        />

        <h3 className="text-xl font-semibold text-white mt-8 mb-3">
          Scene Structure
        </h3>
        <CodeBlock
          code={`// GLB Scene Hierarchy
root
├── massing (Mesh)
│   ├── podium (Mesh)
│   └── tower (Mesh)
├── parcel_boundary (LineLoop)
├── setback_lines (Group)
│   ├── front_setback
│   ├── side_setback_left
│   ├── side_setback_right
│   └── rear_setback
└── context (Group)
    ├── ground_plane
    └── north_arrow`}
          language="text"
          title="Scene Hierarchy"
        />

        <h2 id="obj-format" className="text-2xl font-semibold text-white mt-12 mb-4">
          <Layers className="inline h-6 w-6 mr-2 text-[hsl(var(--data-cyan))]" />
          OBJ Format
        </h2>
        <p className="text-white/70 mb-4">
          Wavefront OBJ format for CAD software compatibility. Exports include 
          a companion MTL file for materials.
        </p>

        <div className="p-4 rounded-lg border border-white/10 bg-white/5 mb-6">
          <h4 className="text-white font-medium mb-3">Specifications</h4>
          <ul className="space-y-2 text-sm text-white/70">
            <li>• <strong>Format Version:</strong> Wavefront OBJ 3.0</li>
            <li>• <strong>Units:</strong> Feet (Texas survey foot)</li>
            <li>• <strong>Materials:</strong> MTL file with basic Phong</li>
            <li>• <strong>Typical Size:</strong> 5-20 MB (OBJ + MTL)</li>
            <li>• <strong>Groups:</strong> Named by building element</li>
          </ul>
        </div>

        <CodeBlock
          code={`# massing.obj excerpt
# SiteIntel CityEngine Export
# Units: feet

mtllib massing.mtl

g podium
v 0.0 0.0 0.0
v 200.0 0.0 0.0
v 200.0 45.0 0.0
v 0.0 45.0 0.0
# ... vertices continue

g tower
v 50.0 45.0 0.0
v 150.0 45.0 0.0
# ... tower vertices

f 1 2 3 4
# ... faces continue`}
          language="text"
          title="OBJ File Structure"
        />

        <h2 id="png-renders" className="text-2xl font-semibold text-white mt-12 mb-4">
          <Image className="inline h-6 w-6 mr-2 text-emerald-400" />
          PNG Renders
        </h2>
        <p className="text-white/70 mb-4">
          Pre-rendered views for presentations, reports, and thumbnails. 
          Multiple camera angles are generated per job.
        </p>

        <div className="overflow-x-auto mb-8">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-white/10">
                <th className="text-left py-3 px-4 text-white">View</th>
                <th className="text-left py-3 px-4 text-white">Resolution</th>
                <th className="text-left py-3 px-4 text-white">Camera Position</th>
              </tr>
            </thead>
            <tbody className="text-white/70">
              <tr className="border-b border-white/10">
                <td className="py-3 px-4 font-mono text-[hsl(var(--data-cyan))]">aerial</td>
                <td className="py-3 px-4">1920 × 1080</td>
                <td className="py-3 px-4">45° from NE, 300ft altitude</td>
              </tr>
              <tr className="border-b border-white/10">
                <td className="py-3 px-4 font-mono text-[hsl(var(--data-cyan))]">street</td>
                <td className="py-3 px-4">1920 × 1080</td>
                <td className="py-3 px-4">Eye-level from primary frontage</td>
              </tr>
              <tr className="border-b border-white/10">
                <td className="py-3 px-4 font-mono text-[hsl(var(--data-cyan))]">corner</td>
                <td className="py-3 px-4">1920 × 1080</td>
                <td className="py-3 px-4">30° elevation from SE corner</td>
              </tr>
              <tr className="border-b border-white/10">
                <td className="py-3 px-4 font-mono text-[hsl(var(--data-cyan))]">plan</td>
                <td className="py-3 px-4">1920 × 1920</td>
                <td className="py-3 px-4">Orthographic top-down</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="p-4 rounded-lg border border-white/10 bg-white/5 mb-6">
          <h4 className="text-white font-medium mb-3">Render Settings</h4>
          <ul className="space-y-2 text-sm text-white/70">
            <li>• <strong>Format:</strong> PNG with alpha channel</li>
            <li>• <strong>Color Depth:</strong> 8-bit per channel (32-bit RGBA)</li>
            <li>• <strong>Background:</strong> Transparent (for compositing)</li>
            <li>• <strong>Shadows:</strong> Soft shadows, sun angle from metadata</li>
            <li>• <strong>Anti-aliasing:</strong> 4x MSAA</li>
          </ul>
        </div>

        <h2 id="manifest-schema" className="text-2xl font-semibold text-white mt-12 mb-4">
          Output Manifest
        </h2>
        <p className="text-white/70 mb-4">
          Every completed job includes a <code>manifest.json</code> with metadata 
          and file paths:
        </p>

        <CodeBlock
          code={`{
  "version": "1.0",
  "job_id": "ce_abc123",
  "created_at": "2025-01-13T14:30:00Z",
  "application_id": "app_xyz789",
  "variant_id": "hotel_v1",
  
  "formats": {
    "glb": {
      "path": "massing.glb",
      "size_bytes": 4521984,
      "draco_compressed": true
    },
    "obj": {
      "path": "massing.obj",
      "mtl_path": "massing.mtl",
      "size_bytes": 8934521
    }
  },
  
  "views": {
    "aerial": { "path": "view_aerial.png", "width": 1920, "height": 1080 },
    "street": { "path": "view_street.png", "width": 1920, "height": 1080 },
    "corner": { "path": "view_corner.png", "width": 1920, "height": 1080 }
  },
  
  "compliance": {
    "max_height_ft": 120,
    "actual_height_ft": 118.5,
    "max_far": 2.5,
    "actual_far": 2.34,
    "setback_front_ft": 15,
    "setback_side_ft": 10,
    "setback_rear_ft": 20,
    "gross_sf": 145000,
    "footprint_sf": 12500
  },
  
  "cga_rules": {
    "preset": "hotel_v1",
    "version": "2025.1.0",
    "parameters": {
      "tower_floors": 12,
      "podium_floors": 3,
      "floor_to_floor_ft": 10.5
    }
  }
}`}
          language="json"
          title="manifest.json"
        />
      </div>
    </DocsLayout>
  );
};

export default ExportFormats;
