import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const logStep = (step: string, details?: any) => {
  const detailsStr = details ? ` - ${JSON.stringify(details)}` : '';
  console.log(`[ADMIN-USAGE-TIMESERIES] ${step}${detailsStr}`);
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  const supabaseAdmin = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
    { auth: { persistSession: false } }
  );

  try {
    logStep("Function started");

    // Get authenticated user
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      throw new Error("Authentication required");
    }

    const token = authHeader.replace("Bearer ", "");
    const { data: userData, error: userError } = await supabaseAdmin.auth.getUser(token);
    
    if (userError || !userData.user) {
      throw new Error("User not authenticated");
    }

    const user = userData.user;
    
    // Get account_id from profile
    const { data: profile } = await supabaseAdmin
      .from("profiles")
      .select("account_id")
      .eq("id", user.id)
      .single();

    const accountId = profile?.account_id || user.id;

    // Parse query params
    const url = new URL(req.url);
    const yyyymm = url.searchParams.get("yyyymm") || `${new Date().getFullYear()}${String(new Date().getMonth() + 1).padStart(2, '0')}`;
    
    logStep("Fetching timeseries", { accountId, yyyymm });

    // Parse yyyymm to get date range
    const year = parseInt(yyyymm.substring(0, 4));
    const month = parseInt(yyyymm.substring(4, 6)) - 1; // 0-indexed
    const startDate = new Date(year, month, 1);
    const endDate = new Date(year, month + 1, 0); // Last day of month

    // Get reports generated by day for this account
    const { data: reports, error: reportsError } = await supabaseAdmin
      .from("applications")
      .select("created_at, status")
      .eq("user_id", user.id)
      .gte("created_at", startDate.toISOString())
      .lte("created_at", endDate.toISOString())
      .order("created_at", { ascending: true });

    if (reportsError) {
      logStep("Error fetching reports", { error: reportsError.message });
    }

    // Aggregate reports by day
    const reportsByDay: Record<string, number> = {};
    const daysInMonth = endDate.getDate();
    
    // Initialize all days with 0
    for (let d = 1; d <= daysInMonth; d++) {
      const dayStr = `${year}-${String(month + 1).padStart(2, '0')}-${String(d).padStart(2, '0')}`;
      reportsByDay[dayStr] = 0;
    }

    // Count reports per day
    (reports || []).forEach(report => {
      const dayStr = report.created_at.substring(0, 10);
      if (reportsByDay[dayStr] !== undefined) {
        reportsByDay[dayStr]++;
      }
    });

    // Convert to array format for charts
    const reportsTimeseries = Object.entries(reportsByDay).map(([date, count]) => ({
      date,
      reports: count,
    }));

    // Get payment history for revenue tracking
    const { data: payments } = await supabaseAdmin
      .from("payment_history")
      .select("created_at, amount_cents, payment_type")
      .eq("user_id", user.id)
      .gte("created_at", startDate.toISOString())
      .lte("created_at", endDate.toISOString())
      .order("created_at", { ascending: true });

    // Aggregate payments by day
    const paymentsByDay: Record<string, { amount_cents: number; count: number }> = {};
    
    for (let d = 1; d <= daysInMonth; d++) {
      const dayStr = `${year}-${String(month + 1).padStart(2, '0')}-${String(d).padStart(2, '0')}`;
      paymentsByDay[dayStr] = { amount_cents: 0, count: 0 };
    }

    (payments || []).forEach(payment => {
      const dayStr = payment.created_at.substring(0, 10);
      if (paymentsByDay[dayStr]) {
        paymentsByDay[dayStr].amount_cents += payment.amount_cents || 0;
        paymentsByDay[dayStr].count++;
      }
    });

    const paymentsTimeseries = Object.entries(paymentsByDay).map(([date, data]) => ({
      date,
      amount_cents: data.amount_cents,
      transactions: data.count,
    }));

    const response = {
      period: yyyymm,
      account_id: accountId,
      reports: {
        total: reports?.length || 0,
        timeseries: reportsTimeseries,
      },
      payments: {
        total_cents: payments?.reduce((sum, p) => sum + (p.amount_cents || 0), 0) || 0,
        transaction_count: payments?.length || 0,
        timeseries: paymentsTimeseries,
      },
      // Recent reports list
      recent_reports: (reports || []).slice(-20).map(r => ({
        created_at: r.created_at,
        status: r.status,
      })),
    };

    logStep("Timeseries generated", { 
      period: yyyymm, 
      reportCount: response.reports.total,
      paymentCount: response.payments.transaction_count,
    });

    return new Response(JSON.stringify(response), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
      status: 200,
    });
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : "Failed to get usage timeseries";
    logStep("ERROR", { message: errorMessage });
    return new Response(JSON.stringify({ error: errorMessage }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
      status: 500,
    });
  }
});
