-- First, make geom column nullable to allow seed data without spatial polygons
ALTER TABLE zoning_canonical ALTER COLUMN geom DROP NOT NULL;

-- Seed Austin Zoning Districts (~39 base districts)
-- Based on City of Austin Land Development Code Chapter 25-2
-- Note: geom column left NULL - actual polygons will be ingested via ETL

INSERT INTO zoning_canonical (
  district_code, district_name, jurisdiction, 
  height_limit, height_limit_stories, far, lot_coverage,
  front_setback, side_setback, rear_setback, corner_setback,
  min_lot_size, min_lot_width,
  permitted_uses, conditional_uses, prohibited_uses,
  source_dataset, dataset_version
) VALUES
-- AUSTIN RESIDENTIAL DISTRICTS
('SF-1', 'Single-Family Residence - Large Lot', 'austin', 32, 2, 0.40, 40, 40, 15, 20, 25, 10000, 80, 'Single-family detached, Accessory dwelling unit, Home occupation, Family home, Group home class I', 'Bed and breakfast, Group home class II, Private secondary educational facility', 'Multifamily, Retail sales, Restaurant, Office, Industrial, Warehouse', 'austin_ldc', 'seed_v1'),
('SF-2', 'Single-Family Residence - Standard Lot', 'austin', 32, 2, 0.40, 40, 25, 5, 10, 15, 5750, 50, 'Single-family detached, Accessory dwelling unit, Home occupation, Family home, Group home class I', 'Bed and breakfast, Duplex residential, Group home class II', 'Multifamily, Retail sales, Restaurant, Office, Industrial', 'austin_ldc', 'seed_v1'),
('SF-3', 'Single-Family Residence - Small Lot', 'austin', 32, 2, 0.40, 45, 25, 5, 10, 15, 5750, 50, 'Single-family detached, Duplex residential, Accessory dwelling unit, Home occupation, Two-family residential', 'Bed and breakfast, Group home class II, Small lot subdivision', 'Multifamily 3+, Retail sales, Restaurant, Office, Industrial', 'austin_ldc', 'seed_v1'),
('SF-4A', 'Single-Family Residence - Condominium', 'austin', 32, 2, 0.45, 50, 15, 5, 10, 10, 3500, 35, 'Single-family attached, Condominium residential, Townhouse, Home occupation', 'Bed and breakfast, Group home class II', 'Multifamily, Retail sales, Restaurant, Industrial', 'austin_ldc', 'seed_v1'),
('SF-5', 'Single-Family Residence - Urban Home', 'austin', 32, 2, 0.45, 55, 15, 0, 5, 10, 2500, 25, 'Single-family attached, Townhouse, Row house, Urban home, Home occupation', 'Duplex residential, Group home class II', 'Multifamily, Retail sales, Industrial', 'austin_ldc', 'seed_v1'),
('SF-6', 'Single-Family Residence - Townhouse', 'austin', 35, 3, 0.50, 60, 10, 0, 5, 10, 2000, 20, 'Townhouse, Row house, Single-family attached, Home occupation', 'Live/work, Group home class II', 'Multifamily, Retail sales, Industrial', 'austin_ldc', 'seed_v1'),
-- AUSTIN MULTIFAMILY DISTRICTS
('MF-1', 'Multifamily Residence - Low Density', 'austin', 40, 3, 0.50, 50, 15, 10, 10, 15, 8000, 60, 'Multifamily, Single-family, Duplex, Triplex, Fourplex, Group home class I', 'Bed and breakfast, Group home class II, Boarding house', 'Retail sales, Restaurant, Office general, Industrial', 'austin_ldc', 'seed_v1'),
('MF-2', 'Multifamily Residence - Low-Medium Density', 'austin', 50, 4, 0.60, 55, 15, 10, 10, 15, 8000, 60, 'Multifamily, Single-family, Duplex, Apartment, Condominium', 'Boarding house, Group home class II, Retirement housing', 'Retail sales, Restaurant general, Office general, Industrial', 'austin_ldc', 'seed_v1'),
('MF-3', 'Multifamily Residence - Medium Density', 'austin', 55, 4, 0.75, 60, 15, 10, 10, 15, 8000, 60, 'Multifamily, Apartment complex, Condominium, Retirement housing', 'Boarding house, Group residential, Congregate living', 'Retail sales, Restaurant general, Industrial', 'austin_ldc', 'seed_v1'),
('MF-4', 'Multifamily Residence - Medium-High Density', 'austin', 60, 5, 1.00, 65, 15, 10, 10, 15, 8000, 60, 'Multifamily high-density, Apartment tower, Condominium, Senior housing', 'Mixed-use residential, Live/work, Congregate living', 'Retail sales general, Industrial', 'austin_ldc', 'seed_v1'),
('MF-5', 'Multifamily Residence - High Density', 'austin', 90, 8, 2.00, 70, 10, 10, 10, 10, 8000, 60, 'Multifamily high-rise, Apartment tower, Condominium tower, Mixed-use residential', 'Live/work, Hotel residential, Congregate living', 'Industrial, Warehouse', 'austin_ldc', 'seed_v1'),
('MF-6', 'Multifamily Residence - Highest Density', 'austin', NULL, NULL, 3.00, 80, 0, 0, 0, 0, 8000, 60, 'Multifamily unlimited, High-rise residential, Mixed-use tower', 'Hotel, Live/work', 'Heavy industrial, Outdoor storage', 'austin_ldc', 'seed_v1'),
-- AUSTIN OFFICE DISTRICTS
('NO', 'Neighborhood Office', 'austin', 35, 2, 0.50, 60, 10, 0, 0, 10, 5750, 50, 'Office limited, Professional services, Medical office, Financial services', 'Personal services, Day care, Art gallery', 'Retail sales general, Restaurant general, Industrial, Residential', 'austin_ldc', 'seed_v1'),
('LO', 'Limited Office', 'austin', 40, 3, 0.50, 60, 10, 0, 0, 10, 5750, 50, 'Office general, Professional services, Medical clinic, Financial services, Administrative', 'Personal services limited, Day care, Art studio', 'Retail sales, Restaurant, Industrial, Warehouse', 'austin_ldc', 'seed_v1'),
('GO', 'General Office', 'austin', 60, 5, 1.00, 70, 10, 0, 0, 10, 5750, 50, 'Office general, Office high-rise, Professional services, Medical facility, Research facility', 'Restaurant limited, Personal services, Conference center', 'Retail sales general, Industrial, Warehouse', 'austin_ldc', 'seed_v1'),
-- AUSTIN COMMERCIAL DISTRICTS
('LR', 'Neighborhood Commercial', 'austin', 40, 3, 0.50, 70, 10, 0, 0, 10, 5750, 50, 'Retail sales limited, Personal services, Restaurant limited, Office limited', 'Day care, Veterinary clinic, Convenience storage', 'Bar/cocktail lounge, Drive-through, Auto sales, Industrial', 'austin_ldc', 'seed_v1'),
('GR', 'Community Commercial', 'austin', 60, 5, 1.00, 80, 0, 0, 0, 0, 5750, 50, 'Retail sales general, Restaurant general, Personal services, Office, Hotel/motel', 'Drive-through, Cocktail lounge, Automotive rentals, Outdoor entertainment', 'Adult entertainment, Heavy industrial, Junkyard', 'austin_ldc', 'seed_v1'),
('CS', 'General Commercial Services', 'austin', 60, 5, 1.00, 95, 0, 0, 0, 0, 5750, 50, 'Retail sales, Restaurant, Auto sales, Auto repair, Building materials, Equipment sales', 'Outdoor entertainment, Gas station, Car wash, Mini-warehouse', 'Heavy industrial, Junkyard, Slaughterhouse', 'austin_ldc', 'seed_v1'),
('CS-1', 'General Commercial Services - Conditional', 'austin', 60, 5, 1.00, 90, 0, 0, 0, 0, 5750, 50, 'Retail sales, Restaurant, Office, Personal services, Hotel', 'Auto sales, Auto repair, Equipment sales, Gas station', 'Heavy industrial, Outdoor storage large, Junkyard', 'austin_ldc', 'seed_v1'),
('CH', 'Commercial Highway', 'austin', 60, 5, 1.00, 90, 25, 0, 0, 10, 10000, 80, 'Auto sales, Auto repair, Gas station, Truck stop, Building materials, Equipment rental', 'Outdoor storage, RV park, Heavy equipment sales', 'Heavy industrial, Slaughterhouse, Junkyard', 'austin_ldc', 'seed_v1'),
-- AUSTIN DOWNTOWN/CBD DISTRICTS
('CBD', 'Central Business District', 'austin', NULL, NULL, 8.00, 100, 0, 0, 0, 0, 5750, 50, 'Office unlimited, Retail, Restaurant, Hotel, Multifamily, Mixed-use, Entertainment', 'Drive-through, Gas station', 'Industrial, Auto repair, Outdoor storage, Junkyard', 'austin_ldc', 'seed_v1'),
('DMU', 'Downtown Mixed-Use', 'austin', NULL, NULL, 8.00, 100, 0, 0, 0, 0, 5750, 50, 'Mixed-use, Office, Retail, Restaurant, Hotel, Multifamily, Entertainment, Cultural', 'Drive-through', 'Industrial, Auto repair, Warehouse, Junkyard', 'austin_ldc', 'seed_v1'),
-- AUSTIN INDUSTRIAL DISTRICTS
('LI', 'Limited Industrial', 'austin', 60, 4, 0.50, 70, 25, 10, 10, 20, 10000, 100, 'Light manufacturing, Warehouse, Distribution, Office, Research facility, Flex space', 'Outdoor storage screened, Food processing, Printing', 'Heavy industrial, Hazardous materials, Junkyard, Residential', 'austin_ldc', 'seed_v1'),
('MI', 'Major Industry', 'austin', 60, 4, 0.50, 60, 30, 20, 20, 25, 43560, 150, 'Heavy manufacturing, Processing plant, Warehouse, Distribution center, Industrial park', 'Hazardous materials storage, Recycling center, Concrete batch plant', 'Residential, Retail, Restaurant, School, Hospital', 'austin_ldc', 'seed_v1'),
('IP', 'Industrial Park', 'austin', 60, 4, 0.50, 65, 50, 25, 25, 35, 43560, 200, 'Light manufacturing, Research facility, Office, Warehouse, Data center, Flex space', 'Limited retail, Restaurant for employees', 'Heavy industrial, Residential, Hazardous materials, Junkyard', 'austin_ldc', 'seed_v1'),
-- AUSTIN MIXED-USE DISTRICTS  
('MU', 'Mixed-Use', 'austin', 60, 5, 1.00, 80, 0, 0, 10, 0, 5750, 50, 'Mixed-use building, Retail ground floor, Office, Multifamily, Live/work, Restaurant', 'Hotel, Entertainment venue, Cultural facility', 'Industrial, Auto repair, Drive-through, Outdoor storage', 'austin_ldc', 'seed_v1'),
('V', 'Vertical Mixed-Use', 'austin', NULL, NULL, 3.00, 90, 0, 0, 0, 0, 5750, 50, 'Vertical mixed-use, Ground floor retail required, Office above, Residential above, Hotel', 'Entertainment, Cultural facility', 'Industrial, Auto uses, Drive-through, Single-use retail', 'austin_ldc', 'seed_v1'),
-- AUSTIN SPECIAL PURPOSE DISTRICTS
('P', 'Public', 'austin', 60, 4, 0.50, 50, 25, 15, 15, 20, 10000, 100, 'Government facility, Public school, Library, Community center, Park, Fire station, Police station', 'Utility facility, Communication tower', 'Residential, Commercial, Industrial', 'austin_ldc', 'seed_v1'),
('PUD', 'Planned Unit Development', 'austin', NULL, NULL, NULL, NULL, 0, 0, 0, 0, NULL, NULL, 'As specified in PUD ordinance', 'As specified in PUD ordinance', 'As specified in PUD ordinance', 'austin_ldc', 'seed_v1'),
('TOD', 'Transit Oriented Development', 'austin', NULL, NULL, 4.00, 90, 0, 0, 0, 0, 5750, 50, 'Mixed-use, Multifamily, Office, Retail, Transit facilities, Hotel', 'Structured parking', 'Auto-oriented uses, Drive-through, Gas station, Surface parking', 'austin_ldc', 'seed_v1'),
('W/LO', 'Waterfront/Lake Office', 'austin', 35, 2, 0.40, 45, 40, 20, 25, 25, 10000, 80, 'Office limited, Residential limited, Marina, Recreation', 'Restaurant limited, Retail limited', 'Industrial, High-intensity commercial, High-density residential', 'austin_ldc', 'seed_v1'),
('AG', 'Agricultural', 'austin', 35, 2, 0.10, 10, 50, 25, 25, 50, 217800, 200, 'Agriculture, Ranching, Single-family residential, Farm stand', 'Agritourism, Stable, Veterinary clinic', 'Commercial, Industrial, Multifamily, Retail', 'austin_ldc', 'seed_v1'),
('RR', 'Rural Residential', 'austin', 35, 2, 0.20, 20, 40, 15, 25, 30, 43560, 150, 'Single-family residential, Agriculture, Home occupation, Stable', 'Bed and breakfast, Veterinary clinic', 'Commercial, Industrial, Multifamily', 'austin_ldc', 'seed_v1'),
('DR', 'Development Reserve', 'austin', 35, 2, 0.05, 5, 100, 50, 50, 100, 435600, 500, 'Agriculture, Single-family residential on existing lots', 'Development per future zoning', 'Subdivision, Commercial, Industrial', 'austin_ldc', 'seed_v1'),
-- SAN ANTONIO RESIDENTIAL DISTRICTS
('RE', 'Residential Estate', 'san_antonio', 35, 2, NULL, 35, 15, 5, 30, 10, 43560, 100, 'Single-family detached, Home occupation, Accessory structure', 'Group home, Family care home, Private school', 'Multifamily, Commercial, Industrial, Retail', 'satx_udc', 'seed_v1'),
('R-20', 'Single-Family Residential 20,000 SF', 'san_antonio', 35, 2, NULL, 40, 15, 5, 20, 10, 20000, 100, 'Single-family detached, Home occupation, Accessory dwelling unit', 'Group home small, Day care home, Bed and breakfast', 'Multifamily, Commercial, Industrial', 'satx_udc', 'seed_v1'),
('R-6', 'Single-Family Residential 6,000 SF', 'san_antonio', 35, 2, NULL, 45, 10, 5, 20, 10, 6000, 50, 'Single-family detached, Home occupation, Accessory dwelling unit', 'Duplex, Group home small, Day care home', 'Multifamily 3+, Commercial, Industrial', 'satx_udc', 'seed_v1'),
('R-5', 'Single-Family Residential 5,000 SF', 'san_antonio', 35, 2, NULL, 50, 10, 5, 20, 10, 5000, 45, 'Single-family detached, Duplex, Home occupation, Accessory dwelling unit', 'Group home small, Day care home, Bed and breakfast', 'Multifamily 3+, Commercial general, Industrial', 'satx_udc', 'seed_v1'),
('R-4', 'Single-Family Residential 4,000 SF', 'san_antonio', 35, 2, NULL, 55, 10, 5, 20, 10, 4000, 40, 'Single-family detached, Duplex, Patio home, Home occupation', 'Triplex, Group home, Day care home', 'Multifamily 4+, Commercial general, Industrial', 'satx_udc', 'seed_v1'),
('R-3', 'Single-Family Residential 3,000 SF', 'san_antonio', 35, 2, NULL, 60, 10, 3, 15, 10, 3000, 35, 'Single-family detached, Duplex, Townhouse, Zero lot line home', 'Triplex, Fourplex, Group home', 'Multifamily 5+, Commercial general, Industrial', 'satx_udc', 'seed_v1'),
-- SAN ANTONIO MULTIFAMILY DISTRICTS
('RM-4', 'Residential Mixed 4,000 SF', 'san_antonio', 35, 3, NULL, 55, 10, 5, 20, 10, 4000, 40, 'Single-family, Duplex, Townhouse, Low-density multifamily', 'Triplex, Fourplex, Group home, Day care center', 'Commercial general, Industrial, High-density multifamily', 'satx_udc', 'seed_v1'),
('RM-5', 'Residential Mixed 5,000 SF', 'san_antonio', 35, 3, NULL, 50, 10, 5, 20, 10, 5000, 45, 'Single-family, Duplex, Townhouse, Low-density multifamily', 'Group home, Day care center, Assisted living', 'Commercial general, Industrial', 'satx_udc', 'seed_v1'),
('RM-6', 'Residential Mixed 6,000 SF', 'san_antonio', 35, 3, NULL, 45, 10, 5, 20, 10, 6000, 50, 'Single-family, Duplex, Townhouse, Garden apartment', 'Group home, Day care center', 'Commercial general, Industrial', 'satx_udc', 'seed_v1'),
('MF-18', 'Multifamily 18 units/acre', 'san_antonio', 35, 3, NULL, 60, 20, 5, 10, 15, 8000, 60, 'Multifamily apartment, Condominium, Townhouse, Single-family', 'Day care center, Group home, Assisted living', 'Commercial general, Industrial, Retail sales', 'satx_udc', 'seed_v1'),
('MF-25', 'Multifamily 25 units/acre', 'san_antonio', 40, 3, NULL, 65, 15, 5, 10, 15, 8000, 60, 'Multifamily apartment, Condominium, Mid-rise residential', 'Day care center, Assisted living, Community facility', 'Commercial general, Industrial', 'satx_udc', 'seed_v1'),
('MF-33', 'Multifamily 33 units/acre', 'san_antonio', 45, 4, NULL, 70, 10, 5, 10, 10, 10000, 80, 'Multifamily apartment, High-rise residential, Mixed-use residential', 'Day care center, Community facility, Retail limited', 'Industrial, Heavy commercial', 'satx_udc', 'seed_v1'),
('MF-40', 'Multifamily 40 units/acre', 'san_antonio', 60, 5, NULL, 75, 10, 5, 10, 10, 10000, 80, 'Multifamily high-rise, Mixed-use tower, Urban residential', 'Retail ground floor, Day care, Community facility', 'Industrial, Heavy commercial', 'satx_udc', 'seed_v1'),
('MF-50', 'Multifamily 50 units/acre', 'san_antonio', 75, 6, NULL, 80, 5, 5, 10, 5, 10000, 80, 'Multifamily high-rise, Mixed-use tower, Urban core residential', 'Retail ground floor, Hotel', 'Industrial, Heavy commercial, Auto uses', 'satx_udc', 'seed_v1'),
('MF-65', 'Multifamily 65 units/acre', 'san_antonio', NULL, NULL, NULL, 85, 0, 5, 10, 0, 10000, 80, 'Multifamily unlimited, High-rise residential, Mixed-use tower', 'Hotel, Entertainment', 'Industrial, Auto uses', 'satx_udc', 'seed_v1'),
-- SAN ANTONIO OFFICE DISTRICTS
('O-1', 'Office Low-Intensity', 'san_antonio', 25, 2, 0.50, 50, 35, 20, 30, 25, 10000, 80, 'Office low-intensity, Professional services, Medical office small', 'Day care center, Personal services limited', 'Retail general, Restaurant, Industrial, Residential', 'satx_udc', 'seed_v1'),
('O-1.5', 'Office Transitional', 'san_antonio', 35, 3, 0.75, 55, 25, 15, 25, 20, 10000, 80, 'Office general, Professional services, Medical clinic, Financial services', 'Day care center, Personal services, Restaurant limited', 'Retail general, Industrial, Warehouse', 'satx_udc', 'seed_v1'),
('O-2', 'Office High-Intensity', 'san_antonio', NULL, NULL, 1.00, 70, 20, 10, 20, 15, 10000, 80, 'Office high-rise, Corporate headquarters, Medical facility, Research facility', 'Hotel, Conference center, Restaurant', 'Retail general, Industrial, Warehouse', 'satx_udc', 'seed_v1'),
-- SAN ANTONIO COMMERCIAL DISTRICTS
('NC', 'Neighborhood Commercial', 'san_antonio', 25, 2, 0.50, 60, 20, 10, 30, 15, 10000, 80, 'Retail sales limited, Personal services, Restaurant limited, Office limited', 'Day care center, Veterinary clinic', 'Drive-through, Auto sales, Industrial, Bar/tavern', 'satx_udc', 'seed_v1'),
('C-1', 'Commercial Light', 'san_antonio', 35, 3, 0.75, 70, 10, 10, 30, 10, 10000, 80, 'Retail sales, Restaurant, Personal services, Office, Hotel/motel', 'Drive-through, Gas station, Veterinary clinic', 'Heavy commercial, Industrial, Adult entertainment', 'satx_udc', 'seed_v1'),
('C-2', 'Commercial General', 'san_antonio', 60, 5, 1.00, 80, 0, 10, 30, 0, 10000, 80, 'Retail sales, Restaurant, Auto sales, Auto service, Office, Hotel, Entertainment', 'Outdoor entertainment, Gas station, Car wash', 'Heavy industrial, Junkyard, Adult entertainment', 'satx_udc', 'seed_v1'),
('C-3', 'Commercial Highway', 'san_antonio', 60, 5, 1.00, 85, 0, 0, 20, 0, 15000, 100, 'Auto sales, Auto repair, Gas station, Truck stop, Building materials, Equipment sales', 'Outdoor storage, RV sales, Heavy equipment', 'Heavy industrial, Junkyard', 'satx_udc', 'seed_v1'),
-- SAN ANTONIO DOWNTOWN/CBD DISTRICTS
('D', 'Downtown', 'san_antonio', NULL, NULL, 12.00, 100, 0, 0, 0, 0, 5000, 50, 'Mixed-use, Office unlimited, Retail, Restaurant, Hotel, Multifamily, Entertainment, Cultural', 'Drive-through with design review', 'Industrial, Auto repair, Junkyard, Surface parking lot', 'satx_udc', 'seed_v1'),
('FBZD', 'Form-Based Zone District', 'san_antonio', NULL, NULL, NULL, NULL, 0, 0, 0, 0, NULL, NULL, 'As specified by transect zone', 'As specified by transect zone', 'As specified by transect zone', 'satx_udc', 'seed_v1'),
-- SAN ANTONIO INDUSTRIAL DISTRICTS
('I-1', 'Industrial Light', 'san_antonio', 60, 4, 0.50, 70, 30, 30, 30, 30, 20000, 100, 'Light manufacturing, Warehouse, Distribution, Office, Research facility, Flex space', 'Outdoor storage screened, Food processing, Recycling limited', 'Heavy industrial, Hazardous materials, Junkyard, Residential', 'satx_udc', 'seed_v1'),
('I-2', 'Industrial Heavy', 'san_antonio', 60, 4, 0.50, 60, 30, 50, 50, 30, 43560, 150, 'Heavy manufacturing, Processing plant, Warehouse, Distribution center, Industrial park', 'Hazardous materials storage, Recycling center, Concrete batch plant', 'Residential, Retail, Restaurant, School, Hospital, Day care', 'satx_udc', 'seed_v1'),
('BP', 'Business Park', 'san_antonio', 60, 4, 0.60, 65, 40, 25, 25, 30, 43560, 200, 'Office campus, Light manufacturing, Research facility, Data center, Flex space', 'Limited retail for employees, Restaurant for employees, Day care', 'Heavy industrial, Residential, Hazardous materials', 'satx_udc', 'seed_v1'),
-- SAN ANTONIO SPECIAL PURPOSE DISTRICTS
('MXD', 'Mixed-Use District', 'san_antonio', 60, 5, 2.00, 80, 0, 0, 10, 0, 10000, 80, 'Mixed-use building, Retail ground floor, Office above, Multifamily above, Live/work', 'Hotel, Entertainment venue', 'Industrial, Auto repair, Outdoor storage, Single-use auto', 'satx_udc', 'seed_v1'),
('SATX-TOD', 'Transit Oriented Development', 'san_antonio', NULL, NULL, 4.00, 90, 0, 0, 0, 0, 10000, 80, 'Mixed-use, Multifamily, Office, Retail, Transit facilities, Hotel', 'Structured parking', 'Auto-oriented uses, Drive-through, Gas station, Surface parking', 'satx_udc', 'seed_v1'),
('IDZ', 'Infill Development Zone', 'san_antonio', NULL, NULL, 3.00, 85, 0, 0, 5, 0, 5000, 50, 'Mixed-use, Multifamily, Townhouse, Office, Retail, Live/work', 'Hotel, Cultural facility', 'Industrial, Auto uses, Drive-through', 'satx_udc', 'seed_v1'),
('FR', 'Farm and Ranch', 'san_antonio', 35, 2, 0.10, 10, 50, 25, 25, 50, 217800, 200, 'Agriculture, Ranching, Single-family residential, Farm stand', 'Agritourism, Stable, Veterinary clinic', 'Commercial, Industrial, Multifamily, Retail', 'satx_udc', 'seed_v1'),
('UD', 'Urban Development', 'san_antonio', 35, 2, 0.20, 30, 35, 10, 25, 25, 43560, 150, 'Single-family residential, Agriculture, Home occupation', 'Development per future zoning', 'Commercial, Industrial, Multifamily dense', 'satx_udc', 'seed_v1');

-- Create indexes for efficient lookups
CREATE INDEX IF NOT EXISTS idx_zoning_canonical_jurisdiction ON zoning_canonical(jurisdiction);
CREATE INDEX IF NOT EXISTS idx_zoning_canonical_code_jurisdiction ON zoning_canonical(district_code, jurisdiction);
CREATE INDEX IF NOT EXISTS idx_zoning_canonical_dataset_version ON zoning_canonical(dataset_version);