-- Update the RPC function to use ST_DWithin for more flexible spatial matching
-- This accounts for census tract boundary precision issues

CREATE OR REPLACE FUNCTION get_demographics_for_point(
  p_lat DOUBLE PRECISION,
  p_lng DOUBLE PRECISION
)
RETURNS TABLE (
  geoid TEXT,
  acs_vintage TEXT,
  county_fips TEXT,
  total_population BIGINT,
  population_density_sqmi NUMERIC,
  median_age NUMERIC,
  under_18_pct NUMERIC,
  working_age_pct NUMERIC,
  over_65_pct NUMERIC,
  white_pct NUMERIC,
  black_pct NUMERIC,
  asian_pct NUMERIC,
  hispanic_pct NUMERIC,
  two_or_more_races_pct NUMERIC,
  total_housing_units BIGINT,
  occupied_housing_units BIGINT,
  vacant_housing_units BIGINT,
  vacancy_rate NUMERIC,
  owner_occupied_pct NUMERIC,
  renter_occupied_pct NUMERIC,
  median_home_value NUMERIC,
  median_rent NUMERIC,
  median_year_built INTEGER,
  median_rooms NUMERIC,
  avg_household_size NUMERIC,
  single_family_pct NUMERIC,
  multi_family_pct NUMERIC,
  median_household_income NUMERIC,
  per_capita_income NUMERIC,
  mean_household_income NUMERIC,
  median_earnings NUMERIC,
  poverty_rate NUMERIC,
  snap_recipients_pct NUMERIC,
  gini_index NUMERIC,
  income_below_50k_pct NUMERIC,
  income_50k_100k_pct NUMERIC,
  income_above_100k_pct NUMERIC,
  labor_force BIGINT,
  employed_population BIGINT,
  unemployment_rate NUMERIC,
  work_from_home_pct NUMERIC,
  white_collar_pct NUMERIC,
  blue_collar_pct NUMERIC,
  service_sector_pct NUMERIC,
  retail_workers BIGINT,
  healthcare_workers BIGINT,
  professional_services_workers BIGINT,
  manufacturing_workers BIGINT,
  top_industries JSONB,
  mean_commute_time_min NUMERIC,
  drive_alone_pct NUMERIC,
  carpool_pct NUMERIC,
  public_transit_pct NUMERIC,
  walk_bike_pct NUMERIC,
  work_from_home_commute_pct NUMERIC,
  commute_under_30min_pct NUMERIC,
  commute_over_60min_pct NUMERIC,
  less_than_high_school_pct NUMERIC,
  high_school_only_pct NUMERIC,
  some_college_pct NUMERIC,
  bachelors_pct NUMERIC,
  graduate_degree_pct NUMERIC,
  stem_degree_pct NUMERIC,
  retail_spending_index NUMERIC,
  workforce_availability_score NUMERIC,
  growth_potential_index NUMERIC,
  affluence_concentration NUMERIC,
  labor_pool_depth NUMERIC,
  daytime_population_estimate NUMERIC,
  population_cagr NUMERIC,
  income_cagr NUMERIC,
  housing_value_cagr NUMERIC,
  rent_cagr NUMERIC,
  population_5yr_projection BIGINT,
  median_income_5yr_projection NUMERIC,
  median_home_value_5yr_projection NUMERIC,
  median_rent_5yr_projection NUMERIC,
  growth_trajectory TEXT,
  market_outlook TEXT,
  projection_confidence NUMERIC,
  accuracy_tier INTEGER,
  confidence NUMERIC,
  source_dataset TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    d.geoid,
    d.acs_vintage,
    d.county_fips,
    d.total_population,
    d.population_density_sqmi,
    d.median_age,
    d.under_18_pct,
    d.working_age_pct,
    d.over_65_pct,
    d.white_pct,
    d.black_pct,
    d.asian_pct,
    d.hispanic_pct,
    d.two_or_more_races_pct,
    d.total_housing_units,
    d.occupied_housing_units,
    d.vacant_housing_units,
    d.vacancy_rate,
    d.owner_occupied_pct,
    d.renter_occupied_pct,
    d.median_home_value,
    d.median_rent,
    d.median_year_built,
    d.median_rooms,
    d.avg_household_size,
    d.single_family_pct,
    d.multi_family_pct,
    d.median_household_income,
    d.per_capita_income,
    d.mean_household_income,
    d.median_earnings,
    d.poverty_rate,
    d.snap_recipients_pct,
    d.gini_index,
    d.income_below_50k_pct,
    d.income_50k_100k_pct,
    d.income_above_100k_pct,
    d.labor_force,
    d.employed_population,
    d.unemployment_rate,
    d.work_from_home_pct,
    d.white_collar_pct,
    d.blue_collar_pct,
    d.service_sector_pct,
    d.retail_workers,
    d.healthcare_workers,
    d.professional_services_workers,
    d.manufacturing_workers,
    d.top_industries,
    d.mean_commute_time_min,
    d.drive_alone_pct,
    d.carpool_pct,
    d.public_transit_pct,
    d.walk_bike_pct,
    d.work_from_home_commute_pct,
    d.commute_under_30min_pct,
    d.commute_over_60min_pct,
    d.less_than_high_school_pct,
    d.high_school_only_pct,
    d.some_college_pct,
    d.bachelors_pct,
    d.graduate_degree_pct,
    d.stem_degree_pct,
    d.retail_spending_index,
    d.workforce_availability_score,
    d.growth_potential_index,
    d.affluence_concentration,
    d.labor_pool_depth,
    d.daytime_population_estimate,
    p.population_cagr,
    p.income_cagr,
    p.housing_value_cagr,
    p.rent_cagr,
    p.population_5yr_projection,
    p.median_income_5yr_projection,
    p.median_home_value_5yr_projection,
    p.median_rent_5yr_projection,
    p.growth_trajectory,
    p.market_outlook,
    p.projection_confidence,
    d.accuracy_tier,
    d.confidence,
    d.source_dataset
  FROM public.canonical_demographics d
  LEFT JOIN public.demographics_projections p ON d.geoid = p.geoid
  WHERE d.geom IS NOT NULL
    AND ST_DWithin(
      d.geom::geography,
      ST_SetSRID(ST_Point(p_lng, p_lat), 4326)::geography,
      500  -- 500 meter tolerance for boundary precision issues
    )
  ORDER BY d.geom::geography <-> ST_SetSRID(ST_Point(p_lng, p_lat), 4326)::geography
  LIMIT 1;
END;
$$;